export const LOGINREQ = "LOGINREQ";
export const LOGINSUCCESS = "LOGINSUCCESS";
export const LOGINFAILURE = "LOGINFAILURE";

export const THREADIDSUCCESS = "THREADIDSUCCESS";
export const THREADIDREQ = "THREADIDREQ";
export const THREADIDFAIL = "THREADIDFAIL";

export const DELETETHREAD_REQ ="DELETETHREAD_REQ"
export const DELETETHREAD_SUCCESS ="DELETETHREAD_SUCCESS"
export const DELETETHREAD_FAIL ="DELETETHREAD_FAIL"